import type { GradedVocabularyTopicData } from "./graded-vocabulary.types.ts";

const COMMUNITY_REFERENCE_DESCRIPTION =
  "20 từ đại diện theo phân loại tham chiếu cộng đồng, không phải danh sách chính thức của JLPT.";

const SOURCE_NAME =
  "Jonathan Waller JLPT Resources, curated by stephenmk/yomitan-jlpt-vocab";
const SOURCE_URL =
  "https://github.com/stephenmk/yomitan-jlpt-vocab/tree/b062d4e38c4bdd0950ae1d4ec55f04b176182e03/original_data";
const SOURCE_LICENSE =
  "CC BY-SA 4.0; upstream Jonathan Waller data licensed CC BY";
const SOURCE_VERSION =
  "stephenmk/yomitan-jlpt-vocab@b062d4e38c4bdd0950ae1d4ec55f04b176182e03";

export const gradedJapaneseVocabulary = [
  {
    id: "tieng-nhat-jlpt-n5",
    title: "Tiếng Nhật · JLPT N5",
    description: COMMUNITY_REFERENCE_DESCRIPTION,
    languageCode: "ja",
    icon: "🌸",
    accent: "rose",
    order: 110,
    framework: "JLPT",
    level: "N5",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    sourceLicense: SOURCE_LICENSE,
    sourceVersion: SOURCE_VERSION,
    words: [
      { id: "n5-au", term: "会う", meaning: "gặp", pronunciation: "あう" },
      { id: "n5-ao", term: "青", meaning: "màu xanh lam", pronunciation: "あお" },
      { id: "n5-akai", term: "赤い", meaning: "màu đỏ", pronunciation: "あかい" },
      { id: "n5-asa", term: "朝", meaning: "buổi sáng", pronunciation: "あさ" },
      { id: "n5-ashita", term: "明日", meaning: "ngày mai", pronunciation: "あした" },
      { id: "n5-atsui", term: "暑い", meaning: "nóng (thời tiết)", pronunciation: "あつい" },
      { id: "n5-iu", term: "言う", meaning: "nói", pronunciation: "いう" },
      { id: "n5-ie", term: "家", meaning: "ngôi nhà", pronunciation: "いえ" },
      { id: "n5-iku", term: "行く", meaning: "đi", pronunciation: "いく" },
      { id: "n5-nomu", term: "飲む", meaning: "uống", pronunciation: "のむ" },
      { id: "n5-taberu", term: "食べる", meaning: "ăn", pronunciation: "たべる" },
      { id: "n5-miru", term: "見る", meaning: "nhìn, xem", pronunciation: "みる" },
      { id: "n5-kiku", term: "聞く", meaning: "nghe; hỏi", pronunciation: "きく" },
      { id: "n5-gakkou", term: "学校", meaning: "trường học", pronunciation: "がっこう" },
      { id: "n5-sensei", term: "先生", meaning: "giáo viên", pronunciation: "せんせい" },
      { id: "n5-gakusei", term: "学生", meaning: "học sinh, sinh viên", pronunciation: "がくせい" },
      { id: "n5-kyou", term: "今日", meaning: "hôm nay", pronunciation: "きょう" },
      { id: "n5-tomodachi", term: "友達", meaning: "bạn bè", pronunciation: "ともだち" },
      { id: "n5-mizu", term: "水", meaning: "nước", pronunciation: "みず" },
      { id: "n5-hon", term: "本", meaning: "sách", pronunciation: "ほん" },
    ],
  },
  {
    id: "tieng-nhat-jlpt-n4",
    title: "Tiếng Nhật · JLPT N4",
    description: COMMUNITY_REFERENCE_DESCRIPTION,
    languageCode: "ja",
    icon: "🗾",
    accent: "violet",
    order: 111,
    framework: "JLPT",
    level: "N4",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    sourceLicense: SOURCE_LICENSE,
    sourceVersion: SOURCE_VERSION,
    words: [
      { id: "n4-anzen", term: "安全", meaning: "an toàn", pronunciation: "あんぜん" },
      { id: "n4-annai", term: "案内", meaning: "hướng dẫn", pronunciation: "あんない" },
      { id: "n4-ika", term: "以下", meaning: "dưới, không quá", pronunciation: "いか" },
      { id: "n4-igai", term: "以外", meaning: "ngoại trừ", pronunciation: "いがい" },
      { id: "n4-ikiru", term: "生きる", meaning: "sống", pronunciation: "いきる" },
      { id: "n4-iken", term: "意見", meaning: "ý kiến", pronunciation: "いけん" },
      { id: "n4-ichido", term: "一度", meaning: "một lần", pronunciation: "いちど" },
      { id: "n4-isshoukenmei", term: "一生懸命", meaning: "hết sức", pronunciation: "いっしょうけんめい" },
      { id: "n4-utsuru", term: "移る", meaning: "chuyển, dời", pronunciation: "うつる" },
      { id: "n4-unten", term: "運転", meaning: "lái xe", pronunciation: "うんてん" },
      { id: "n4-undou", term: "運動", meaning: "vận động, tập thể dục", pronunciation: "うんどう" },
      { id: "n4-kaigi", term: "会議", meaning: "cuộc họp", pronunciation: "かいぎ" },
      { id: "n4-kaijou", term: "会場", meaning: "địa điểm tổ chức", pronunciation: "かいじょう" },
      { id: "n4-kankei", term: "関係", meaning: "quan hệ", pronunciation: "かんけい" },
      { id: "n4-keiken", term: "経験", meaning: "kinh nghiệm", pronunciation: "けいけん" },
      { id: "n4-kenkyuu", term: "研究", meaning: "nghiên cứu", pronunciation: "けんきゅう" },
      { id: "n4-koshou", term: "故障", meaning: "hỏng hóc", pronunciation: "こしょう" },
      { id: "n4-saikin", term: "最近", meaning: "gần đây", pronunciation: "さいきん" },
      { id: "n4-setsumei", term: "説明", meaning: "giải thích", pronunciation: "せつめい" },
      { id: "n4-hitsuyou", term: "必要", meaning: "cần thiết", pronunciation: "ひつよう" },
    ],
  },
  {
    id: "tieng-nhat-jlpt-n3",
    title: "Tiếng Nhật · JLPT N3",
    description: COMMUNITY_REFERENCE_DESCRIPTION,
    languageCode: "ja",
    icon: "⛩️",
    accent: "rose",
    order: 112,
    framework: "JLPT",
    level: "N3",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    sourceLicense: SOURCE_LICENSE,
    sourceVersion: SOURCE_VERSION,
    words: [
      { id: "n3-ai", term: "愛", meaning: "tình yêu", pronunciation: "あい" },
      { id: "n3-aizu", term: "合図", meaning: "tín hiệu", pronunciation: "あいず" },
      { id: "n3-aite", term: "相手", meaning: "đối phương, bạn đồng hành", pronunciation: "あいて" },
      { id: "n3-akiraka", term: "明らか", meaning: "rõ ràng", pronunciation: "あきらか" },
      { id: "n3-akirameru", term: "諦める", meaning: "từ bỏ", pronunciation: "あきらめる" },
      { id: "n3-atsukau", term: "扱う", meaning: "xử lý, đối xử", pronunciation: "あつかう" },
      { id: "n3-ayamari", term: "誤り", meaning: "sai sót", pronunciation: "あやまり" },
      { id: "n3-antei", term: "安定", meaning: "ổn định", pronunciation: "あんてい" },
      { id: "n3-igai", term: "意外", meaning: "ngoài dự đoán", pronunciation: "いがい" },
      { id: "n3-ishi", term: "医師", meaning: "bác sĩ", pronunciation: "いし" },
      { id: "n3-iji", term: "維持", meaning: "duy trì", pronunciation: "いじ" },
      { id: "n3-ishiki", term: "意識", meaning: "ý thức", pronunciation: "いしき" },
      { id: "n3-ippou", term: "一方", meaning: "mặt khác; một phía", pronunciation: "いっぽう" },
      { id: "n3-ichi", term: "位置", meaning: "vị trí", pronunciation: "いち" },
      { id: "n3-idou", term: "移動", meaning: "di chuyển", pronunciation: "いどう" },
      { id: "n3-inochi", term: "命", meaning: "sinh mạng", pronunciation: "いのち" },
      { id: "n3-inshou", term: "印象", meaning: "ấn tượng", pronunciation: "いんしょう" },
      { id: "n3-intai", term: "引退", meaning: "nghỉ hưu, giải nghệ", pronunciation: "いんたい" },
      { id: "n3-eikyou", term: "影響", meaning: "ảnh hưởng", pronunciation: "えいきょう" },
      { id: "n3-kaiketsu", term: "解決", meaning: "giải quyết", pronunciation: "かいけつ" },
    ],
  },
  {
    id: "tieng-nhat-jlpt-n2",
    title: "Tiếng Nhật · JLPT N2",
    description: COMMUNITY_REFERENCE_DESCRIPTION,
    languageCode: "ja",
    icon: "🈶",
    accent: "violet",
    order: 113,
    framework: "JLPT",
    level: "N2",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    sourceLicense: SOURCE_LICENSE,
    sourceVersion: SOURCE_VERSION,
    words: [
      { id: "n2-aikawarazu", term: "あいかわらず", meaning: "vẫn như thường", pronunciation: "あいかわらず" },
      { id: "n2-aimai", term: "曖昧", meaning: "mơ hồ", pronunciation: "あいまい" },
      { id: "n2-au", term: "遭う", meaning: "gặp phải điều xấu", pronunciation: "あう" },
      { id: "n2-aojiroi", term: "青白い", meaning: "tái nhợt", pronunciation: "あおじろい" },
      { id: "n2-akegata", term: "明け方", meaning: "rạng sáng", pronunciation: "あけがた" },
      { id: "n2-akogareru", term: "憧れる", meaning: "ngưỡng mộ, khao khát", pronunciation: "あこがれる" },
      { id: "n2-ashiato", term: "足跡", meaning: "dấu chân", pronunciation: "あしあと" },
      { id: "n2-ajiwau", term: "味わう", meaning: "nếm, thưởng thức", pronunciation: "あじわう" },
      { id: "n2-azukaru", term: "預かる", meaning: "giữ hộ", pronunciation: "あずかる" },
      { id: "n2-atatamaru", term: "暖まる", meaning: "ấm lên", pronunciation: "あたたまる" },
      { id: "n2-atarimae", term: "あたりまえ", meaning: "đương nhiên", pronunciation: "あたりまえ" },
      { id: "n2-asshuku", term: "圧縮", meaning: "nén", pronunciation: "あっしゅく" },
      { id: "n2-abareru", term: "暴れる", meaning: "quậy phá", pronunciation: "あばれる" },
      { id: "n2-amaru", term: "余る", meaning: "dư thừa", pronunciation: "あまる" },
      { id: "n2-amu", term: "編む", meaning: "đan, biên soạn", pronunciation: "あむ" },
      { id: "n2-ayaui", term: "危うい", meaning: "nguy hiểm", pronunciation: "あやうい" },
      { id: "n2-arasou", term: "争う", meaning: "tranh giành", pronunciation: "あらそう" },
      { id: "n2-aratameru", term: "改める", meaning: "sửa đổi", pronunciation: "あらためる" },
      { id: "n2-arigatai", term: "有難い", meaning: "đáng quý, biết ơn", pronunciation: "ありがたい" },
      { id: "n2-igi", term: "意義", meaning: "ý nghĩa, giá trị", pronunciation: "いぎ" },
    ],
  },
  {
    id: "tieng-nhat-jlpt-n1",
    title: "Tiếng Nhật · JLPT N1",
    description: COMMUNITY_REFERENCE_DESCRIPTION,
    languageCode: "ja",
    icon: "🎌",
    accent: "rose",
    order: 114,
    framework: "JLPT",
    level: "N1",
    sourceName: SOURCE_NAME,
    sourceUrl: SOURCE_URL,
    sourceLicense: SOURCE_LICENSE,
    sourceVersion: SOURCE_VERSION,
    words: [
      { id: "n1-aiso", term: "愛想", meaning: "sự niềm nở", pronunciation: "あいそ" },
      { id: "n1-aidagara", term: "間柄", meaning: "mối quan hệ", pronunciation: "あいだがら" },
      { id: "n1-aizou", term: "愛憎", meaning: "yêu ghét", pronunciation: "あいぞう" },
      { id: "n1-aete", term: "敢えて", meaning: "cố ý, dám", pronunciation: "あえて" },
      { id: "n1-aogu", term: "仰ぐ", meaning: "ngước nhìn, kính trọng", pronunciation: "あおぐ" },
      { id: "n1-akashi", term: "証", meaning: "bằng chứng", pronunciation: "あかし" },
      { id: "n1-akaji", term: "赤字", meaning: "thâm hụt", pronunciation: "あかじ" },
      { id: "n1-akasu", term: "明かす", meaning: "tiết lộ", pronunciation: "あかす" },
      { id: "n1-azamuku", term: "欺く", meaning: "lừa dối", pronunciation: "あざむく" },
      { id: "n1-azayaka", term: "鮮やか", meaning: "rực rỡ", pronunciation: "あざやか" },
      { id: "n1-aseru", term: "焦る", meaning: "sốt ruột", pronunciation: "あせる" },
      { id: "n1-ataisuru", term: "値する", meaning: "xứng đáng", pronunciation: "あたいする" },
      { id: "n1-akka", term: "悪化", meaning: "xấu đi", pronunciation: "あっか" },
      { id: "n1-appaku", term: "圧迫", meaning: "gây áp lực, áp bức", pronunciation: "あっぱく" },
      { id: "n1-atsukai", term: "扱い", meaning: "cách đối xử", pronunciation: "あつかい" },
      { id: "n1-atomawashi", term: "後回し", meaning: "trì hoãn", pronunciation: "あとまわし" },
      { id: "n1-afureru", term: "溢れる", meaning: "tràn đầy", pronunciation: "あふれる" },
      { id: "n1-ayatsuru", term: "操る", meaning: "điều khiển", pronunciation: "あやつる" },
      { id: "n1-arakajime", term: "予め", meaning: "trước", pronunciation: "あらかじめ" },
      { id: "n1-arisama", term: "有様", meaning: "tình trạng", pronunciation: "ありさま" },
    ],
  },
] satisfies readonly GradedVocabularyTopicData[];
