import type { GradedVocabularyTopicData } from "./graded-vocabulary.types.ts";

// Danh sách cấp độ được đối chiếu với đề cương HSK phát hành tháng 11/2025,
// có hiệu lực từ tháng 07/2026:
// https://hsk.cn-bj.ufileos.com/3.0/%E6%96%B0%E7%89%88HSK%E8%80%83%E8%AF%95%E5%A4%A7%E7%BA%B2%EF%BC%88%E8%AF%8D%E6%B1%87%E3%80%81%E6%B1%89%E5%AD%97%E3%80%81%E8%AF%AD%E6%B3%95%EF%BC%89.pdf
const source = {
  sourceName: "New HSK (2025) word lists — krmanik/HSK-3.0",
  sourceUrl:
    "https://github.com/krmanik/HSK-3.0/tree/182692ce5a11bc30bdc771835d2f0f27491c25de/New%20HSK%20%282025%29",
  sourceLicense: "CC BY-SA 4.0; nghĩa tiếng Việt do Lingora tự biên soạn",
  sourceVersion: "HSK 3.0, đề cương 2025 (hiệu lực 07/2026), commit 182692ce",
} as const;

export const gradedChineseVocabulary: readonly GradedVocabularyTopicData[] = [
  {
    id: "tieng-trung-hsk-1",
    title: "Tiếng Trung · HSK 1",
    description: "20 từ đại diện cho HSK 1 theo đề cương hiện hành, dành cho người mới bắt đầu.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 120,
    framework: "HSK",
    level: "1",
    ...source,
    words: [
      { id: "wo", term: "我", pronunciation: "wǒ", meaning: "tôi" },
      { id: "ni", term: "你", pronunciation: "nǐ", meaning: "bạn" },
      { id: "ta-nam", term: "他", pronunciation: "tā", meaning: "anh ấy; ông ấy" },
      { id: "ta-nu", term: "她", pronunciation: "tā", meaning: "cô ấy; bà ấy" },
      { id: "shi", term: "是", pronunciation: "shì", meaning: "là" },
      { id: "you", term: "有", pronunciation: "yǒu", meaning: "có" },
      { id: "zai", term: "在", pronunciation: "zài", meaning: "ở; đang" },
      { id: "ai", term: "爱", pronunciation: "ài", meaning: "yêu; thích" },
      { id: "jia", term: "家", pronunciation: "jiā", meaning: "nhà; gia đình" },
      { id: "xuexiao", term: "学校", pronunciation: "xuéxiào", meaning: "trường học" },
      { id: "laoshi", term: "老师", pronunciation: "lǎoshī", meaning: "giáo viên" },
      { id: "xuesheng", term: "学生", pronunciation: "xuéshēng", meaning: "học sinh; sinh viên" },
      { id: "pengyou", term: "朋友", pronunciation: "péngyou", meaning: "bạn bè" },
      { id: "shui", term: "水", pronunciation: "shuǐ", meaning: "nước" },
      { id: "mifan", term: "米饭", pronunciation: "mǐfàn", meaning: "cơm" },
      { id: "chi", term: "吃", pronunciation: "chī", meaning: "ăn" },
      { id: "he", term: "喝", pronunciation: "hē", meaning: "uống" },
      { id: "kan", term: "看", pronunciation: "kàn", meaning: "nhìn; xem" },
      { id: "ting", term: "听", pronunciation: "tīng", meaning: "nghe" },
      { id: "shuo", term: "说", pronunciation: "shuō", meaning: "nói" },
    ],
  },
  {
    id: "tieng-trung-hsk-2",
    title: "Tiếng Trung · HSK 2",
    description: "20 từ đại diện cho HSK 2 theo đề cương hiện hành, mở rộng giao tiếp hằng ngày.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 121,
    framework: "HSK",
    level: "2",
    ...source,
    words: [
      { id: "bangmang", term: "帮忙", pronunciation: "bāngmáng", meaning: "giúp đỡ" },
      { id: "ditie", term: "地铁", pronunciation: "dìtiě", meaning: "tàu điện ngầm" },
      { id: "luyou", term: "旅游", pronunciation: "lǚyóu", meaning: "du lịch" },
      { id: "yundong", term: "运动", pronunciation: "yùndòng", meaning: "vận động; thể thao" },
      { id: "shengri", term: "生日", pronunciation: "shēngrì", meaning: "sinh nhật" },
      { id: "jichang", term: "机场", pronunciation: "jīchǎng", meaning: "sân bay" },
      { id: "yanse", term: "颜色", pronunciation: "yánsè", meaning: "màu sắc" },
      { id: "paobu", term: "跑步", pronunciation: "pǎobù", meaning: "chạy bộ" },
      { id: "xiwang", term: "希望", pronunciation: "xīwàng", meaning: "hy vọng; mong muốn" },
      { id: "shiqing", term: "事情", pronunciation: "shìqing", meaning: "sự việc; công việc" },
      { id: "jieshao", term: "介绍", pronunciation: "jièshào", meaning: "giới thiệu" },
      { id: "dakai", term: "打开", pronunciation: "dǎkāi", meaning: "mở ra; bật lên" },
      { id: "kaoshi", term: "考试", pronunciation: "kǎoshì", meaning: "kỳ thi; thi" },
      { id: "kafei", term: "咖啡", pronunciation: "kāfēi", meaning: "cà phê" },
      { id: "kuaile", term: "快乐", pronunciation: "kuàilè", meaning: "vui vẻ" },
      { id: "shenti", term: "身体", pronunciation: "shēntǐ", meaning: "cơ thể; sức khỏe" },
      { id: "shufu", term: "舒服", pronunciation: "shūfu", meaning: "dễ chịu; thoải mái" },
      { id: "youyong", term: "游泳", pronunciation: "yóuyǒng", meaning: "bơi; bơi lội" },
      { id: "zhunbei", term: "准备", pronunciation: "zhǔnbèi", meaning: "chuẩn bị" },
      { id: "ziji", term: "自己", pronunciation: "zìjǐ", meaning: "bản thân; tự mình" },
    ],
  },
  {
    id: "tieng-trung-hsk-3",
    title: "Tiếng Trung · HSK 3",
    description: "20 từ đại diện cho HSK 3 theo đề cương hiện hành, phục vụ học tập và đời sống.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 122,
    framework: "HSK",
    level: "3",
    ...source,
    words: [
      { id: "anquan", term: "安全", pronunciation: "ānquán", meaning: "an toàn" },
      { id: "banfa", term: "办法", pronunciation: "bànfǎ", meaning: "cách; biện pháp" },
      { id: "canjia", term: "参加", pronunciation: "cānjiā", meaning: "tham gia" },
      { id: "bixu", term: "必须", pronunciation: "bìxū", meaning: "phải; bắt buộc" },
      { id: "chengji", term: "成绩", pronunciation: "chéngjì", meaning: "thành tích; điểm số" },
      { id: "zhongyao", term: "重要", pronunciation: "zhòngyào", meaning: "quan trọng" },
      { id: "xuyao", term: "需要", pronunciation: "xūyào", meaning: "cần; nhu cầu" },
      { id: "yingxiang", term: "影响", pronunciation: "yǐngxiǎng", meaning: "ảnh hưởng" },
      { id: "xuanze", term: "选择", pronunciation: "xuǎnzé", meaning: "lựa chọn; chọn" },
      { id: "liaojie", term: "了解", pronunciation: "liǎojiě", meaning: "tìm hiểu; hiểu rõ" },
      { id: "wenhua", term: "文化", pronunciation: "wénhuà", meaning: "văn hóa" },
      { id: "huanjing", term: "环境", pronunciation: "huánjìng", meaning: "môi trường" },
      { id: "xinwen", term: "新闻", pronunciation: "xīnwén", meaning: "tin tức" },
      { id: "xiguan", term: "习惯", pronunciation: "xíguàn", meaning: "thói quen; quen với" },
      { id: "jiankang", term: "健康", pronunciation: "jiànkāng", meaning: "khỏe mạnh; sức khỏe" },
      { id: "jiejue", term: "解决", pronunciation: "jiějué", meaning: "giải quyết" },
      { id: "faxian", term: "发现", pronunciation: "fāxiàn", meaning: "phát hiện" },
      { id: "jihui", term: "机会", pronunciation: "jīhuì", meaning: "cơ hội" },
      { id: "guanxi", term: "关系", pronunciation: "guānxì", meaning: "quan hệ; mối liên hệ" },
      { id: "renwei", term: "认为", pronunciation: "rènwéi", meaning: "cho rằng" },
    ],
  },
  {
    id: "tieng-trung-hsk-4",
    title: "Tiếng Trung · HSK 4",
    description: "20 từ đại diện cho HSK 4 theo đề cương hiện hành, hướng tới giao tiếp độc lập.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 123,
    framework: "HSK",
    level: "4",
    ...source,
    words: [
      { id: "anpai", term: "安排", pronunciation: "ānpái", meaning: "sắp xếp; bố trí" },
      { id: "baohu", term: "保护", pronunciation: "bǎohù", meaning: "bảo vệ" },
      { id: "biaozhun", term: "标准", pronunciation: "biāozhǔn", meaning: "tiêu chuẩn" },
      { id: "biye", term: "毕业", pronunciation: "bìyè", meaning: "tốt nghiệp" },
      { id: "biaoshi", term: "表示", pronunciation: "biǎoshì", meaning: "biểu thị; bày tỏ" },
      { id: "keji", term: "科技", pronunciation: "kējì", meaning: "khoa học và công nghệ" },
      { id: "guanli", term: "管理", pronunciation: "guǎnlǐ", meaning: "quản lý" },
      { id: "jishu", term: "技术", pronunciation: "jìshù", meaning: "kỹ thuật; công nghệ" },
      { id: "jingji", term: "经济", pronunciation: "jīngjì", meaning: "kinh tế" },
      { id: "jingyan", term: "经验", pronunciation: "jīngyàn", meaning: "kinh nghiệm" },
      { id: "zeren", term: "责任", pronunciation: "zérèn", meaning: "trách nhiệm" },
      { id: "shihe", term: "适合", pronunciation: "shìhé", meaning: "phù hợp" },
      { id: "shehui", term: "社会", pronunciation: "shèhuì", meaning: "xã hội" },
      { id: "zunzhong", term: "尊重", pronunciation: "zūnzhòng", meaning: "tôn trọng" },
      { id: "taolun", term: "讨论", pronunciation: "tǎolùn", meaning: "thảo luận" },
      { id: "yanjiu", term: "研究", pronunciation: "yánjiū", meaning: "nghiên cứu" },
      { id: "zhiliang", term: "质量", pronunciation: "zhìliàng", meaning: "chất lượng" },
      { id: "zhichi", term: "支持", pronunciation: "zhīchí", meaning: "ủng hộ; hỗ trợ" },
      { id: "jieguo", term: "结果", pronunciation: "jiéguǒ", meaning: "kết quả" },
      { id: "jihua", term: "计划", pronunciation: "jìhuà", meaning: "kế hoạch; lên kế hoạch" },
    ],
  },
  {
    id: "tieng-trung-hsk-5",
    title: "Tiếng Trung · HSK 5",
    description: "20 từ đại diện cho HSK 5 theo đề cương hiện hành, dùng trong chủ đề học thuật và xã hội.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 124,
    framework: "HSK",
    level: "5",
    ...source,
    words: [
      { id: "anwei", term: "安慰", pronunciation: "ānwèi", meaning: "an ủi" },
      { id: "bawo", term: "把握", pronunciation: "bǎwò", meaning: "nắm bắt; nắm chắc" },
      { id: "baochi", term: "保持", pronunciation: "bǎochí", meaning: "duy trì" },
      { id: "beijing", term: "背景", pronunciation: "bèijǐng", meaning: "bối cảnh; nền tảng" },
      { id: "benzhi", term: "本质", pronunciation: "běnzhì", meaning: "bản chất" },
      { id: "bili", term: "比例", pronunciation: "bǐlì", meaning: "tỷ lệ" },
      { id: "biaoda", term: "表达", pronunciation: "biǎodá", meaning: "biểu đạt; diễn đạt" },
      { id: "gongxian", term: "贡献", pronunciation: "gòngxiàn", meaning: "đóng góp; cống hiến" },
      { id: "guandian", term: "观点", pronunciation: "guāndiǎn", meaning: "quan điểm" },
      { id: "hezuo", term: "合作", pronunciation: "hézuò", meaning: "hợp tác" },
      { id: "gaishan", term: "改善", pronunciation: "gǎishàn", meaning: "cải thiện" },
      { id: "ziyuan", term: "资源", pronunciation: "zīyuán", meaning: "tài nguyên; nguồn lực" },
      { id: "tiaozhan", term: "挑战", pronunciation: "tiǎozhàn", meaning: "thách thức" },
      { id: "chuantong", term: "传统", pronunciation: "chuántǒng", meaning: "truyền thống" },
      { id: "zhengju", term: "证据", pronunciation: "zhèngjù", meaning: "bằng chứng" },
      { id: "qushi", term: "趋势", pronunciation: "qūshì", meaning: "xu hướng" },
      { id: "duli", term: "独立", pronunciation: "dúlì", meaning: "độc lập" },
      { id: "qiangdiao", term: "强调", pronunciation: "qiángdiào", meaning: "nhấn mạnh" },
      { id: "shixian", term: "实现", pronunciation: "shíxiàn", meaning: "thực hiện; đạt được" },
      { id: "chengguo", term: "成果", pronunciation: "chéngguǒ", meaning: "thành quả" },
    ],
  },
  {
    id: "tieng-trung-hsk-6",
    title: "Tiếng Trung · HSK 6",
    description: "20 từ đại diện cho HSK 6 theo đề cương hiện hành, mở rộng diễn đạt chuyên sâu.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 125,
    framework: "HSK",
    level: "6",
    ...source,
    words: [
      { id: "anli", term: "案例", pronunciation: "ànlì", meaning: "trường hợp điển hình; vụ việc" },
      { id: "anshi", term: "暗示", pronunciation: "ànshì", meaning: "ám chỉ; gợi ý" },
      { id: "baozhang", term: "保障", pronunciation: "bǎozhàng", meaning: "bảo đảm; bảo vệ" },
      { id: "baolu", term: "暴露", pronunciation: "bàolù", meaning: "phơi bày; lộ ra" },
      { id: "baofa", term: "爆发", pronunciation: "bàofā", meaning: "bùng phát" },
      { id: "beiguan", term: "悲观", pronunciation: "bēiguān", meaning: "bi quan" },
      { id: "benneng", term: "本能", pronunciation: "běnnéng", meaning: "bản năng" },
      { id: "celue", term: "策略", pronunciation: "cèlüè", meaning: "chiến lược" },
      { id: "qianli", term: "潜力", pronunciation: "qiánlì", meaning: "tiềm năng" },
      { id: "xietiao", term: "协调", pronunciation: "xiétiáo", meaning: "phối hợp; điều hòa" },
      { id: "caina", term: "采纳", pronunciation: "cǎinà", meaning: "tiếp thu; chấp nhận" },
      { id: "changjing", term: "场景", pronunciation: "chǎngjǐng", meaning: "bối cảnh; cảnh huống" },
      { id: "chuangban", term: "创办", pronunciation: "chuàngbàn", meaning: "sáng lập" },
      { id: "fuyu", term: "赋予", pronunciation: "fùyǔ", meaning: "trao cho; ban cho" },
      { id: "jinrong", term: "金融", pronunciation: "jīnróng", meaning: "tài chính" },
      { id: "jingque", term: "精确", pronunciation: "jīngquè", meaning: "chính xác" },
      { id: "tixi", term: "体系", pronunciation: "tǐxì", meaning: "hệ thống" },
      { id: "xinlai", term: "信赖", pronunciation: "xìnlài", meaning: "tin cậy" },
      { id: "zhengshi", term: "证实", pronunciation: "zhèngshí", meaning: "xác thực; chứng minh" },
      { id: "zhuzhai", term: "住宅", pronunciation: "zhùzhái", meaning: "nhà ở; khu dân cư" },
    ],
  },
  {
    id: "tieng-trung-hsk-7-9",
    title: "Tiếng Trung · HSK 7–9",
    description: "20 từ đại diện cho bậc nâng cao HSK 7–9 theo đề cương hiện hành.",
    languageCode: "zh",
    icon: "🀄",
    accent: "amber",
    order: 126,
    framework: "HSK",
    level: "7-9",
    ...source,
    words: [
      { id: "aizheng", term: "癌症", pronunciation: "áizhèng", meaning: "ung thư" },
      { id: "ai-bu-shi-shou", term: "爱不释手", pronunciation: "ài bú shì shǒu", meaning: "thích đến mức không nỡ rời tay" },
      { id: "aimei", term: "暧昧", pronunciation: "àimèi", meaning: "mập mờ; không rõ ràng" },
      { id: "anfu", term: "安抚", pronunciation: "ānfǔ", meaning: "xoa dịu; trấn an" },
      { id: "aomi", term: "奥秘", pronunciation: "àomì", meaning: "điều huyền bí; bí ẩn sâu xa" },
      { id: "bazhan", term: "霸占", pronunciation: "bàzhàn", meaning: "chiếm giữ bằng thế lực" },
      { id: "beiai", term: "悲哀", pronunciation: "bēi'āi", meaning: "bi ai; đau buồn" },
      { id: "bianzheng", term: "辩证", pronunciation: "biànzhèng", meaning: "biện chứng" },
      { id: "binlin", term: "濒临", pronunciation: "bīnlín", meaning: "đứng trước bờ vực; sắp rơi vào" },
      { id: "cangbai", term: "苍白", pronunciation: "cāngbái", meaning: "nhợt nhạt; thiếu sức thuyết phục" },
      { id: "chanshu", term: "阐述", pronunciation: "chǎnshù", meaning: "trình bày và giải thích rõ" },
      { id: "chendian", term: "沉淀", pronunciation: "chéndiàn", meaning: "lắng đọng; tích lũy" },
      { id: "dianfan", term: "典范", pronunciation: "diǎnfàn", meaning: "hình mẫu; điển phạm" },
      { id: "dianfu", term: "颠覆", pronunciation: "diānfù", meaning: "lật đổ; đảo lộn" },
      { id: "gongshi", term: "共识", pronunciation: "gòngshí", meaning: "đồng thuận; nhận thức chung" },
      { id: "geju", term: "格局", pronunciation: "géjú", meaning: "cục diện; tầm vóc" },
      { id: "huajie", term: "化解", pronunciation: "huàjiě", meaning: "tháo gỡ; hóa giải" },
      { id: "ke-bu-rong-huan", term: "刻不容缓", pronunciation: "kè bù róng huǎn", meaning: "cấp bách, không thể trì hoãn" },
      { id: "mosuo", term: "摸索", pronunciation: "mōsuǒ", meaning: "dò dẫm tìm cách; tìm tòi" },
      { id: "tuoxie", term: "妥协", pronunciation: "tuǒxié", meaning: "thỏa hiệp" },
    ],
  },
];
