import type { GradedVocabularyTopicData } from "./graded-vocabulary.types.ts";

const cefrJSource = {
  sourceName: "CEFR-J Wordlist",
  sourceUrl: "https://www.cefr-j.org/data/CEFRJ_wordlist_ver1.6.zip",
  sourceLicense:
    "Research and commercial use with proper acknowledgement",
  sourceVersion: "1.6",
} as const;

const octanoveSource = {
  sourceName: "Octanove Vocabulary Profile C1/C2",
  sourceUrl:
    "https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master/octanove-vocabulary-profile-c1c2-1.0.csv",
  sourceLicense: "CC BY-SA 4.0",
  sourceVersion: "1.0",
} as const;

export const gradedEnglishVocabulary = [
  {
    id: "tieng-anh-cefr-a1",
    title: "Tiếng Anh · CEFR A1",
    description: "20 từ tiếng Anh nền tảng dành cho người mới bắt đầu.",
    languageCode: "en",
    icon: "🌱",
    accent: "emerald",
    order: 100,
    framework: "CEFR",
    level: "A1",
    ...cefrJSource,
    words: [
      { id: "apple", term: "apple", meaning: "quả táo", pronunciation: "/ˈæpəɫ/" },
      { id: "beautiful", term: "beautiful", meaning: "đẹp", pronunciation: "/ˈbjutəfəɫ/" },
      { id: "city", term: "city", meaning: "thành phố", pronunciation: "/ˈsɪti/" },
      { id: "clothes", term: "clothes", meaning: "quần áo", pronunciation: "/ˈkɫoʊðz/" },
      { id: "family", term: "family", meaning: "gia đình", pronunciation: "/ˈfæməɫi/" },
      { id: "food", term: "food", meaning: "thức ăn", pronunciation: "/ˈfud/" },
      { id: "friend", term: "friend", meaning: "người bạn", pronunciation: "/ˈfɹɛnd/" },
      { id: "happy", term: "happy", meaning: "vui vẻ", pronunciation: "/ˈhæpi/" },
      { id: "health", term: "health", meaning: "sức khỏe", pronunciation: "/ˈhɛɫθ/" },
      { id: "holiday", term: "holiday", meaning: "kỳ nghỉ", pronunciation: "/ˈhɑɫəˌdeɪ/" },
      { id: "language", term: "language", meaning: "ngôn ngữ", pronunciation: "/ˈɫæŋɡwədʒ/" },
      { id: "library", term: "library", meaning: "thư viện", pronunciation: "/ˈɫaɪbɹɛˌɹi/" },
      { id: "morning", term: "morning", meaning: "buổi sáng", pronunciation: "/ˈmɔɹnɪŋ/" },
      { id: "music", term: "music", meaning: "âm nhạc", pronunciation: "/ˈmjuzɪk/" },
      { id: "restaurant", term: "restaurant", meaning: "nhà hàng", pronunciation: "/ˈɹɛsˌtɹɑnt/" },
      { id: "school", term: "school", meaning: "trường học", pronunciation: "/ˈskuɫ/" },
      { id: "speak", term: "speak", meaning: "nói", pronunciation: "/ˈspik/" },
      { id: "teacher", term: "teacher", meaning: "giáo viên", pronunciation: "/ˈtitʃɝ/" },
      { id: "weather", term: "weather", meaning: "thời tiết", pronunciation: "/ˈwɛðɝ/" },
      { id: "world", term: "world", meaning: "thế giới", pronunciation: "/ˈwɝɫd/" },
    ],
  },
  {
    id: "tieng-anh-cefr-a2",
    title: "Tiếng Anh · CEFR A2",
    description: "20 từ tiếng Anh thiết yếu cho các tình huống quen thuộc.",
    languageCode: "en",
    icon: "🧭",
    accent: "blue",
    order: 101,
    framework: "CEFR",
    level: "A2",
    ...cefrJSource,
    words: [
      { id: "ability", term: "ability", meaning: "khả năng", pronunciation: "/əˈbɪɫəˌti/" },
      { id: "abroad", term: "abroad", meaning: "ở nước ngoài", pronunciation: "/əˈbɹɔd/" },
      { id: "accept", term: "accept", meaning: "chấp nhận", pronunciation: "/əkˈsɛpt/" },
      { id: "accident", term: "accident", meaning: "tai nạn", pronunciation: "/ˈæksədənt/" },
      { id: "advice", term: "advice", meaning: "lời khuyên", pronunciation: "/ædˈvaɪs/" },
      { id: "compare", term: "compare", meaning: "so sánh", pronunciation: "/kəmˈpɛɹ/" },
      { id: "country", term: "country", meaning: "quốc gia", pronunciation: "/ˈkəntɹi/" },
      { id: "danger", term: "danger", meaning: "sự nguy hiểm", pronunciation: "/ˈdeɪndʒɝ/" },
      { id: "decide", term: "decide", meaning: "quyết định", pronunciation: "/ˌdɪˈsaɪd/" },
      { id: "discover", term: "discover", meaning: "khám phá", pronunciation: "/dɪˈskəvɝ/" },
      { id: "explain", term: "explain", meaning: "giải thích", pronunciation: "/ɪksˈpɫeɪn/" },
      { id: "invite", term: "invite", meaning: "mời", pronunciation: "/ˌɪnˈvaɪt/" },
      { id: "journey", term: "journey", meaning: "chuyến đi", pronunciation: "/ˈdʒɝni/" },
      { id: "museum", term: "museum", meaning: "bảo tàng", pronunciation: "/mjuˈziəm/" },
      { id: "prepare", term: "prepare", meaning: "chuẩn bị", pronunciation: "/pɹiˈpɛɹ/" },
      { id: "understand", term: "understand", meaning: "hiểu", pronunciation: "/ˌəndɝˈstænd/" },
      { id: "university", term: "university", meaning: "trường đại học", pronunciation: "/ˌjunəˈvɝsəti/" },
      { id: "useful", term: "useful", meaning: "hữu ích", pronunciation: "/ˈjusfəɫ/" },
      { id: "village", term: "village", meaning: "làng", pronunciation: "/ˈvɪɫədʒ/" },
      { id: "wild", term: "wild", meaning: "hoang dã", pronunciation: "/ˈwaɪɫd/" },
    ],
  },
  {
    id: "tieng-anh-cefr-b1",
    title: "Tiếng Anh · CEFR B1",
    description: "20 từ tiếng Anh trung cấp cho học tập và giao tiếp độc lập.",
    languageCode: "en",
    icon: "🌿",
    accent: "cyan",
    order: 102,
    framework: "CEFR",
    level: "B1",
    ...cefrJSource,
    words: [
      { id: "achievement", term: "achievement", meaning: "thành tựu", pronunciation: "/əˈtʃivmənt/" },
      { id: "accurate", term: "accurate", meaning: "chính xác", pronunciation: "/ˈækjɝət/" },
      { id: "analysis", term: "analysis", meaning: "sự phân tích", pronunciation: "/əˈnæɫɪsɪs/" },
      { id: "anxiety", term: "anxiety", meaning: "sự lo âu", pronunciation: "/æŋˈzaɪəti/" },
      { id: "apparent", term: "apparent", meaning: "có vẻ rõ ràng", pronunciation: "/əˈpɛɹənt/" },
      { id: "assume", term: "assume", meaning: "giả định", pronunciation: "/əˈsum/" },
      { id: "career", term: "career", meaning: "sự nghiệp", pronunciation: "/kɝˈɪɹ/" },
      { id: "complex", term: "complex", meaning: "phức tạp", pronunciation: "/ˈkɑmpɫɛks/" },
      { id: "confidence", term: "confidence", meaning: "sự tự tin", pronunciation: "/ˈkɑnfədəns/" },
      { id: "contain", term: "contain", meaning: "chứa đựng", pronunciation: "/kənˈteɪn/" },
      { id: "contribute", term: "contribute", meaning: "đóng góp", pronunciation: "/kənˈtɹɪbjut/" },
      { id: "decision", term: "decision", meaning: "quyết định", pronunciation: "/dɪˈsɪʒən/" },
      { id: "demonstrate", term: "demonstrate", meaning: "chứng minh", pronunciation: "/ˈdɛmənˌstɹeɪt/" },
      { id: "development", term: "development", meaning: "sự phát triển", pronunciation: "/dɪˈvɛɫəpmənt/" },
      { id: "effective", term: "effective", meaning: "có hiệu quả", pronunciation: "/ɪˈfɛktɪv/" },
      { id: "efficient", term: "efficient", meaning: "hiệu quả, ít lãng phí", pronunciation: "/ɪˈfɪʃənt/" },
      { id: "independent", term: "independent", meaning: "độc lập", pronunciation: "/ˌɪndɪˈpɛndənt/" },
      { id: "maintain", term: "maintain", meaning: "duy trì", pronunciation: "/meɪnˈteɪn/" },
      { id: "participate", term: "participate", meaning: "tham gia", pronunciation: "/pɑɹˈtɪsəˌpeɪt/" },
      { id: "responsible", term: "responsible", meaning: "có trách nhiệm", pronunciation: "/ɹiˈspɑnsəbəɫ/" },
    ],
  },
  {
    id: "tieng-anh-cefr-b2",
    title: "Tiếng Anh · CEFR B2",
    description: "20 từ tiếng Anh trên trung cấp để diễn đạt ý tưởng phức tạp.",
    languageCode: "en",
    icon: "🚀",
    accent: "violet",
    order: 103,
    framework: "CEFR",
    level: "B2",
    ...cefrJSource,
    words: [
      { id: "abolish", term: "abolish", meaning: "bãi bỏ", pronunciation: "/əˈbɑɫɪʃ/" },
      { id: "adequate", term: "adequate", meaning: "đầy đủ, phù hợp", pronunciation: "/ˈædəkwət/" },
      { id: "ambiguous", term: "ambiguous", meaning: "mơ hồ", pronunciation: "/æmˈbɪɡjuəs/" },
      { id: "anticipate", term: "anticipate", meaning: "dự đoán trước", pronunciation: "/ænˈtɪsəˌpeɪt/" },
      { id: "assess", term: "assess", meaning: "đánh giá", pronunciation: "/əˈsɛs/" },
      { id: "assumption", term: "assumption", meaning: "giả định", pronunciation: "/əˈsəmpʃən/" },
      { id: "circumstance", term: "circumstance", meaning: "hoàn cảnh", pronunciation: "/ˈsɝkəmˌstæns/" },
      { id: "coherent", term: "coherent", meaning: "mạch lạc", pronunciation: "/koʊˈhɪɹənt/" },
      { id: "comprehensive", term: "comprehensive", meaning: "toàn diện", pronunciation: "/ˌkɑmpɹiˈhɛnsɪv/" },
      { id: "consistent", term: "consistent", meaning: "nhất quán", pronunciation: "/kənˈsɪstənt/" },
      { id: "contradict", term: "contradict", meaning: "mâu thuẫn, phản bác", pronunciation: "/ˌkɑntɹəˈdɪkt/" },
      { id: "controversy", term: "controversy", meaning: "sự tranh cãi", pronunciation: "/ˈkɑntɹəˌvɝsi/" },
      { id: "cooperate", term: "cooperate", meaning: "hợp tác", pronunciation: "/koʊˈɑpɝˌeɪt/" },
      { id: "crucial", term: "crucial", meaning: "then chốt", pronunciation: "/ˈkɹuʃəɫ/" },
      { id: "evaluate", term: "evaluate", meaning: "đánh giá kỹ", pronunciation: "/ɪˈvæɫjuˌeɪt/" },
      { id: "interpret", term: "interpret", meaning: "diễn giải", pronunciation: "/ˌɪnˈtɝpɹət/" },
      { id: "justify", term: "justify", meaning: "chứng minh là hợp lý", pronunciation: "/ˈdʒəstəˌfaɪ/" },
      { id: "perspective", term: "perspective", meaning: "góc nhìn", pronunciation: "/pɝˈspɛktɪv/" },
      { id: "relevant", term: "relevant", meaning: "có liên quan", pronunciation: "/ˈɹɛɫəvənt/" },
      { id: "valid", term: "valid", meaning: "hợp lệ, có căn cứ", pronunciation: "/ˈvæɫɪd/" },
    ],
  },
  {
    id: "tieng-anh-cefr-c1",
    title: "Tiếng Anh · CEFR C1",
    description: "20 từ tiếng Anh nâng cao để trình bày ý tưởng tinh tế, chính xác.",
    languageCode: "en",
    icon: "🎓",
    accent: "amber",
    order: 104,
    framework: "CEFR",
    level: "C1",
    ...octanoveSource,
    words: [
      { id: "alleviate", term: "alleviate", meaning: "làm dịu", pronunciation: "/əˈɫiviˌeɪt/" },
      { id: "assertion", term: "assertion", meaning: "lời khẳng định", pronunciation: "/əˈsɝʃən/" },
      { id: "collaborate", term: "collaborate", meaning: "cộng tác", pronunciation: "/kəˈɫæbɝˌeɪt/" },
      { id: "compliance", term: "compliance", meaning: "sự tuân thủ", pronunciation: "/kəmˈpɫaɪəns/" },
      { id: "complexity", term: "complexity", meaning: "độ phức tạp", pronunciation: "/kəmˈpɫɛksəti/" },
      { id: "constraint", term: "constraint", meaning: "sự ràng buộc", pronunciation: "/kənˈstɹeɪnt/" },
      { id: "credibility", term: "credibility", meaning: "độ tin cậy", pronunciation: "/ˌkɹɛdəˈbɪɫɪti/" },
      { id: "cynical", term: "cynical", meaning: "hoài nghi, yếm thế", pronunciation: "/ˈsɪnɪkəɫ/" },
      { id: "detrimental", term: "detrimental", meaning: "có hại", pronunciation: "/ˌdɛtɹəˈmɛntəɫ/" },
      { id: "diversity", term: "diversity", meaning: "sự đa dạng", pronunciation: "/daɪˈvɝsɪti/" },
      { id: "embark", term: "embark", meaning: "bắt đầu một hành trình", pronunciation: "/ɪmˈbɑɹk/" },
      { id: "ethical", term: "ethical", meaning: "thuộc về đạo đức", pronunciation: "/ˈɛθɪkəɫ/" },
      { id: "evoke", term: "evoke", meaning: "gợi lên", pronunciation: "/ɪˈvoʊk/" },
      { id: "exert", term: "exert", meaning: "vận dụng, gây ra", pronunciation: "/ɪɡˈzɝt/" },
      { id: "formulate", term: "formulate", meaning: "xây dựng rõ ràng", pronunciation: "/ˈfɔɹmjəˌɫeɪt/" },
      { id: "innovation", term: "innovation", meaning: "sự đổi mới", pronunciation: "/ˌɪnəˈveɪʃən/" },
      { id: "profound", term: "profound", meaning: "sâu sắc", pronunciation: "/pɹoʊˈfaʊnd/" },
      { id: "resilient", term: "resilient", meaning: "kiên cường", pronunciation: "/ɹɪˈzɪɫjənt/" },
      { id: "scrutiny", term: "scrutiny", meaning: "sự xem xét kỹ lưỡng", pronunciation: "/ˈskɹutəni/" },
      { id: "sustainable", term: "sustainable", meaning: "bền vững", pronunciation: "/səˈsteɪnəbəɫ/" },
    ],
  },
  {
    id: "tieng-anh-cefr-c2",
    title: "Tiếng Anh · CEFR C2",
    description: "20 từ tiếng Anh thành thạo có sắc thái học thuật và chuyên sâu.",
    languageCode: "en",
    icon: "🏆",
    accent: "rose",
    order: 105,
    framework: "CEFR",
    level: "C2",
    ...octanoveSource,
    words: [
      { id: "aberration", term: "aberration", meaning: "sự bất thường", pronunciation: "/ˌæbɝˈeɪʃən/" },
      { id: "adhere", term: "adhere", meaning: "tuân thủ", pronunciation: "/ədˈhɪɹ/" },
      { id: "adverse", term: "adverse", meaning: "bất lợi", pronunciation: "/ˈædˌvɝs/" },
      { id: "agility", term: "agility", meaning: "sự nhanh nhẹn", pronunciation: "/əˈdʒɪɫəti/" },
      { id: "anonymity", term: "anonymity", meaning: "sự ẩn danh", pronunciation: "/ˌænəˈnɪmɪti/" },
      { id: "antidote", term: "antidote", meaning: "thuốc giải", pronunciation: "/ˈænɪˌdoʊt/" },
      { id: "aptitude", term: "aptitude", meaning: "năng khiếu", pronunciation: "/ˈæptəˌtud/" },
      { id: "arduous", term: "arduous", meaning: "gian khổ", pronunciation: "/ˈɑɹdʒuəs/" },
      { id: "austerity", term: "austerity", meaning: "sự khắc khổ", pronunciation: "/ˌɔˈstɛɹɪti/" },
      { id: "autonomous", term: "autonomous", meaning: "tự chủ", pronunciation: "/ɔˈtɑnəməs/" },
      { id: "beneficiary", term: "beneficiary", meaning: "người thụ hưởng", pronunciation: "/ˌbɛnəˈfɪʃiˌɛɹi/" },
      { id: "brevity", term: "brevity", meaning: "sự ngắn gọn", pronunciation: "/ˈbɹɛvəti/" },
      { id: "cognitive", term: "cognitive", meaning: "thuộc về nhận thức", pronunciation: "/ˈkɑɡnɪtɪv/" },
      { id: "commodity", term: "commodity", meaning: "hàng hóa", pronunciation: "/kəˈmɑdəti/" },
      { id: "connotation", term: "connotation", meaning: "hàm ý", pronunciation: "/ˌkɑnəˈteɪʃən/" },
      { id: "curriculum", term: "curriculum", meaning: "chương trình học", pronunciation: "/kɝˈɪkjəɫəm/" },
      { id: "disseminate", term: "disseminate", meaning: "phổ biến rộng rãi", pronunciation: "/dɪˈsɛməˌneɪt/" },
      { id: "equilibrium", term: "equilibrium", meaning: "trạng thái cân bằng", pronunciation: "/ˌikwəˈɫɪbɹiəm/" },
      { id: "euphemism", term: "euphemism", meaning: "cách nói giảm nói tránh", pronunciation: "/ˈjufəˌmɪzəm/" },
      { id: "impeccable", term: "impeccable", meaning: "hoàn hảo, không tì vết", pronunciation: "/ˌɪmˈpɛkəbəɫ/" },
    ],
  },
] satisfies readonly GradedVocabularyTopicData[];
