export const COLLECTIONS = {
  auditLogs: "auditLogs",
  contentActivities: "contentActivities",
  contentCourses: "contentCourses",
  contentLessons: "contentLessons",
  contentMedia: "contentMedia",
  contentSources: "contentSources",
  contentUnits: "contentUnits",
  courses: "courses",
  examBlueprints: "examBlueprints",
  examCatalog: "examCatalog",
  examFormVersions: "examFormVersions",
  idempotencyKeys: "idempotencyKeys",
  languages: "languages",
  lexemes: "lexemes",
  programs: "programs",
  publishedCourseRevisions: "publishedCourseRevisions",
  publishedLessonRevisions: "publishedLessonRevisions",
  publishJobs: "publishJobs",
  questions: "questions",
  questionVersions: "questionVersions",
  rateLimits: "rateLimits",
  sourceAttributions: "sourceAttributions",
  systemConfig: "systemConfig",
  users: "users",
  vocabularyTopics: "vocabularyTopics",
  vocabularyWords: "vocabularyWords",
} as const;

export const USER_SUBCOLLECTIONS = {
  attempts: "attempts",
  dailyStats: "dailyStats",
  enrollments: "enrollments",
  lessonProgress: "lessonProgress",
  reviewItems: "reviewItems",
  sections: "sections",
  topicProgress: "topicProgress",
  practiceDays: "practiceDays",
} as const;
